simulation:
  num_months: 12
  num_households: 100
  num_firms: 100
  num_banks: 10
  num_government: 1
  num_laborhours: 100
  num_products: 100
  num_transactions: 100
  num_wages: 100
  num_innovations: 100
  num_research: 100
  num_investments: 100

tax:
  income_tax_rate:
    # by year
    - cutoff: 0
      rate: 0.1
    - cutoff: 11601
      rate: 0.12
    - cutoff: 47151
      rate: 0.22
    - cutoff: 100526
      rate: 0.24
    - cutoff: 191951
      rate: 0.32
    - cutoff: 243726
      rate: 0.35
    - cutoff: 609351
      rate: 0.37
  corporate_tax_rate: 0.21
  vat_rate: 0.08
  fica_tax_rate: 0.0765

  interest:
    # by year
    rate: 0.005

demand list test:
  enable_month1_household_demand_logging_only: False
  demand_logging_unlimited_stock_amount: 1e12
  demand_logging_output_dir: "output/month1_household_demand_3000sku"
  demand_logging_write_csv: True
  demand_logging_run_employment_setup: True
  demand_logging_pay_wages_before_consumption: True

concurrent config:
  max_concurrent_tasks: 100
  max_llm_concurrent: 400

